### ISSUE TITLE
Library maybe not for IDE 2.0 useable

### ISSUE THREAD

**Issue by RasPix** [khoih-prog/RP2040_ISR_Servo#1] opened 2021-09-27 20:01 UTC
### Describe the bug
RP2040_ISR_Servo library in version 1.0.0 not visible in library manager of IDE 2.0.

following Link
https://www.arduino.cc/reference//en/libraries/rp2040_isr_servo/
describe how to include the library in the IDE library. Unfortunately the library is not visible in the library manager of IDE 2.0. 
Trying to include the zip file of the library do not work too. The IDE function "sketch -> include library -> add .zip library" do not work too. It stops with a error message (library ist  not valid: missing header file...)

Could it be possible to add a fully working library into the repository in order to use it with IDE 2.0?

Thanks

**Comment by khoih-prog** [comment] 2021-09-27 20:22
Hi,

Thanks for using the library.

As [**Arduino IDE 2.0**](https://www.arduino.cc/en/software#experimental-software) is still in infancy experimental beta stage, you'll get many more unexpected issues than when using official releases, such as [**Arduino IDE 1.8.16-**](https://www.arduino.cc/en/software). Unless you have real reason to use beta-software, I suggest not to use it because many library writers won't waste time to support the experimental IDE because who knows how many `breaking` changes would be introduced overnight.

You can try [**How to install and use a library with the Arduino IDE 2.0**](https://www.arduino.cc/en/Tutorial/getting-started-with-ide-v2/ide-v2-installing-a-library). If not working, I suggest you post issue on Arduino 2.0 IDE to ask for help because this is their issue to introduce new IDE without using the good old `Library Manager` system

I'm closing the issue now as this is **not a bug of this library** .

**Closed as completed by khoih-prog** 2021-09-27 20:22 UTC
Labels: wontfix, Not this Library
